### ISSUE TITLE
Node modules and env folder zijn naar git gecommited

### ISSUE THREAD

**Issue by TimTerwijn** [randy554/real-time-web-1920#2]
Node modules kosten veel ruimte, git ignore deze.
Mensen kunnen je api key stelen en misbruiken, dan krijg jij de blame, wat de gevolgen ook zijn. Maak gebruik van een heroku environment variable

**Comment by randy554** [comment]
Is opgelost. De bestanden stonden wel in de gitignore maar werden al getracked.
